-- 1. Create stores table
CREATE TABLE IF NOT EXISTS stores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Add store_id to existing tables
ALTER TABLE productos
ADD COLUMN IF NOT EXISTS store_id BIGINT REFERENCES stores(id) ON DELETE CASCADE;

ALTER TABLE ventas
ADD COLUMN IF NOT EXISTS store_id BIGINT REFERENCES stores(id) ON DELETE CASCADE;

ALTER TABLE gastos
ADD COLUMN IF NOT EXISTS store_id BIGINT REFERENCES stores(id) ON DELETE CASCADE;

-- 3. RLS Policies for Stores
ALTER TABLE stores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own stores"
ON stores FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own stores"
ON stores FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own stores"
ON stores FOR UPDATE
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own stores"
ON stores FOR DELETE
USING (auth.uid() = user_id);

-- 4. Update RLS for other tables to check store ownership
-- Note: This is simplified. Ideally, you'd check if the user owns the store the item belongs to.
-- Existing policies likely check auth.uid() = user_id, which is still valid as items are linked to user_id too.
-- However, for strict multi-store isolation, you might want to enforce store_id checks.
-- For now, we rely on the existing user_id checks which are already in place.

-- 5. Storage for Product Images
INSERT INTO storage.buckets (id, name, public)
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO NOTHING;

-- Policy to allow authenticated users to upload images
CREATE POLICY "Authenticated users can upload product images"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'product-images');

-- Policy to allow public to view images
CREATE POLICY "Public can view product images"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'product-images');
